create table public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone not null default now()
);

alter table public.todos enable row level security;

create policy "Todos are readable by everyone"
on public.todos
for select
to anon, authenticated
using (true);
